---
# Drupal Variables
drupal_version: 8.5.3
drupal_site_name: "My Drupal Site"
drupal_admin_username: admin
drupal_admin_pass: StrongPass
drupal_db_user  : drupal-user
drupal_db_name  : drupal-db
drupal_db_pass  : StrongPass
drupal_host : localhost
